# frozen_string_literal: true

# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# stub: rake-version2 2.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rake-version2"
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["AlphaHydrae", "capripot"].freeze
  s.date = "2025-07-12"
  s.description = "Rake tasks to manage your VERSION file. No repository management (tags, committing, pushing), no release management."
  s.email = "capripot@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/rake-version.rb",
    "lib/rake-version/config.rb",
    "lib/rake-version/context.rb",
    "lib/rake-version/copier.rb",
    "lib/rake-version/ext.rb",
    "lib/rake-version/manager.rb",
    "lib/rake-version/tasks.rb",
    "lib/rake-version/version.rb"
  ]
  s.homepage = "https://github.com/capripot/rake-version2"
  s.licenses = ["MIT"]
  s.rubygems_version = ">= 3.4.22"
  s.required_ruby_version = ">= 3.2.8"
  s.summary = "Simple rake tasks for version management."

  s.add_runtime_dependency(%q<rake>, ["> 11.1"])

  s.add_development_dependency(%q<rspec>, ["~> 3.4"])
  s.add_development_dependency(%q<rspec-its>, ["~> 1.2"])
  s.add_development_dependency(%q<bundler>, ["> 1.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
  s.add_development_dependency(%q<simplecov>, ["~> 0.14"])
  s.add_development_dependency(%q<travis-lint>, ["~> 2.0"])
  s.add_development_dependency(%q<fakefs>, ["~> 0.8"])
  s.add_development_dependency(%q<coveralls>, ["~> 0.8"])
end
